# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  labels:
    app: ml-model
spec:
  replicas: 1 # You can increase this for more instances
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model-container
        image: ml-model-image:latest # This image will be built locally by Docker
        imagePullPolicy: Never # Tell Kubernetes to use the local image, not pull from a registry
        ports:
        - containerPort: 5000
